### PR TITLE
Fix session close

### LINKED ISSUE #29: Exception is raised on session close
#28 introduced a little bug - now `asyncio.CancelledError` exception is raised on session close.
Here the task is cancelled:
https://github.com/tipsi/aiozk/blob/341b337a2fc239788fc142eba3633868bd3a8bf1/aiozk/session.py#L311
And here its exception is being catched:
https://github.com/tipsi/aiozk/blob/341b337a2fc239788fc142eba3633868bd3a8bf1/aiozk/session.py#L87
As we know `future.exception()` raises `asyncio.CancelledError` if the future has been cancelled so finally we're getting exception raised.

FYI @cybergrind @nikitagromov

### PR DESCRIPTION
**Pull request by decaz**
Fixes #29.

### CODE REVIEW

**Comment by cybergrind** [comment]
@decaz yeah, fix is good. It would be great if you could add a test that will reproduce this error.

**Comment by decaz** [comment]
@cybergrind how can it be tested? Currently it's impossible to close session within tests, - a lot of methods are mocked.

**Comment by cybergrind** [comment]
I'm not sure what do you mean. You don't need to mock anything to create a session and close it. Probably you're looking into something different. You can easily create a client (without mocking anything) and close session without using mock at all.

**Comment by decaz** [comment]
@cybergrind I don't understand how this should be tested, - it's side effect of `done` callback and code after awaiting `repair_loop_task` continues to be executed. There is no `else` branch within callback to check this side effect.

Also it's strange to test exactly this because it's [documented Python behavior](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.exception) (it should raise `asyncio.CancelledError` by definition) and here we start to test Python itself.

**Comment by cybergrind** [comment]
@decaz fixed in #32

**Pull request closed without merging**
